// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2H6QobHsC2JT07ek41h1IkoBQ2jgR9go',
    appId: '1:424941467453:web:6aa6d1466ceacb72b1f754',
    messagingSenderId: '424941467453',
    projectId: 'suithouseharsh',
    authDomain: 'suithouseharsh.firebaseapp.com',
    storageBucket: 'suithouseharsh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_5DPyncm_igSzTQ1o73CD67_RLr9KNOw',
    appId: '1:394995014357:android:0d28674637fe1c9c33a05c',
    messagingSenderId: '394995014357',
    projectId: 'e-commerce-store-84b01',
    storageBucket: 'e-commerce-store-84b01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSLWvw-areGij5-T34qQ7LlXayeFbGmfs',
    appId: '1:394995014357:ios:a547e712a510d16633a05c',
    messagingSenderId: '394995014357',
    projectId: 'e-commerce-store-84b01',
    storageBucket: 'e-commerce-store-84b01.appspot.com',
    iosBundleId: 'com.example.ssECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8uy9SBEZEbSv3mW6pCqTkt7GvHKaV3a8',
    appId: '1:424941467453:ios:df89581109eab26eb1f754',
    messagingSenderId: '424941467453',
    projectId: 'suithouseharsh',
    storageBucket: 'suithouseharsh.firebasestorage.app',
    iosBundleId: 'com.example.ssECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2H6QobHsC2JT07ek41h1IkoBQ2jgR9go',
    appId: '1:424941467453:web:ebccac4a12433ff9b1f754',
    messagingSenderId: '424941467453',
    projectId: 'suithouseharsh',
    authDomain: 'suithouseharsh.firebaseapp.com',
    storageBucket: 'suithouseharsh.firebasestorage.app',
  );
}
